---
title: "CoA Panel - DNL Liver samples"
author: Alec Trub
output: html_notebook
---

#Generating figures and stats for CoA panel of livers of statin treated mice

## Load libraries
```{r}
library(tidyverse) # for base packages
library(readxl) # to read excel files; part of tidyverse, but not a core part, so need to load it separately
library(janitor) # clean data
library(viridis) # For awesome, accessible color palettes
library(ggrepel) #for smart ggplot labels
library(broom) #for stats
library(cowplot)#for cleaner export
library(scales)
```

##Load data set containing proteins and statistical information. Clean up extra rows
```{r}
df <- read_excel("data/20190814.xlsx",col_names = TRUE)%>%
  remove_empty(c("rows", "cols"))
  
colnames(df)[1] = "Mouse"

df[14] = c("Control","Control", "Statin","Control","Statin","Statin","Control","Statin")
colnames(df)[14] = "Treatment"

df[15] = c("Male","Male", "Male","Male","Male","Male","Female","Female")
colnames(df)[15] = "Sex"

df$Mouse= factor(df$Mouse)

#reformat
dfgraph = df %>% gather(key = "Metabolite", value = "value",2:13)
```


#log transform
```{r}
df_log <- df %>%
  map_if(., is.numeric, log2) %>% 
  as.tibble()

```

#calculate mean, and then normalize each mean
```{r}
#make a 'flat' group a, vector to then operate the 'mean' funtion on
df_log_mean_control <- df_log %>%
  filter(Treatment == "Control") %>%
  summarize_if(is.numeric, mean) %>% 
  flatten_dbl()
df_log_mean_control

#mutate all values by divinding by mean of 'control', and then re-bind to group ID
df_log_rel <- df_log %>%
  select_if(is.numeric) %>%
  map2(., df_log_mean_control, ~ .x - .y) %>%
  bind_cols(select(df_log, Treatment), .)
df_log_rel

#calculate avg
df_log_rel_mean <- df_log_rel %>% 
  group_by(Treatment) %>% 
  summarize_all(funs(mean))
df_log_rel_mean

#long data for plotting
df_log_plot <- df_log_rel_mean %>% 
  gather(key = "Metabolite", value = "FC", -Treatment)
df_log_plot

```
#Average Log Fold Change, shown in paper
```{r}
#Treatment as Factor
df_log_plot$Metabolite = fct_rev(factor(df_log_plot$Metabolite, levels = c("HMG CoA","Malonyl CoA","Acetyl CoA", "Aceto Acetyl CoA","Propionyl CoA","Butyryl CoA","Hydroxybutyryl CoA","Succinyl CoA","Isovaleryl CoA","Glutaryl CoA","Hexanoyl CoA","CoA")))

df_log_plot = df_log_plot %>% 
  mutate(hmg = str_detect(Metabolite,"HMG"))
#Graph FC
miceFC = ggplot(filter(df_log_plot,Treatment == "Statin"))+
  geom_col(aes(reorder(Metabolite,FC),FC,fill = hmg),show.legend = F, color = "black")+
  scale_fill_manual(values = c("black","red"))+
  theme_cowplot()+
  scale_y_continuous(limits = c(-0.25,1.25), breaks = c(-0.2, 0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2))+
  coord_flip()+
  labs(title = "",y = "Log 2 Fold Change")+
  theme(axis.text = element_text(size = 14, face = "bold"),axis.title.y = element_blank())


ggsave("export/CoAStatinTxMice.tiff", height = 5)
```

#seperated by mouse, not in paper
```{r}
#Set factors
dfgraph$Metabolite = fct_rev(factor(dfgraph$Metabolite, levels = c("HMG CoA","Malonyl CoA","Acetyl CoA", "Aceto Acetyl CoA","Propionyl CoA","Butyryl CoA","Hydroxybutyryl CoA","Succinyl CoA","Isovaleryl CoA","Glutaryl CoA","Hexanoyl CoA","CoA")))

#Separate, absolute values 
ggplot(dfgraph)+
  geom_col(aes(x = Metabolite, y = value, fill = as.factor(Mouse)), position = "dodge") +
  scale_fill_viridis(discrete = TRUE)+
  coord_flip()+
  labs(title = "CoA Changes in Statin-Treated Mice",y = "Relative Levels",fill = "Mouse")

#HMG Only
ggplot(filter(dfgraph, Metabolite == "HMG CoA"))+
  geom_col(aes(x = Metabolite, y = value, fill = as.factor(Mouse)), position = "dodge") +
  scale_fill_viridis(discrete = TRUE)+
  coord_flip()+
  labs(y = "Relative Value",x ="",title = "HMG-CoA levels in Statin-Treated Mice",fill = "Mouse")

```



#Stats
```{r}
p_df <- dfgraph %>%
  group_by(Metabolite) %>% 
  nest() %>% #Nest all non-grouping columns into list-frames
  mutate(t_test = map(data, ~tidy(aov(value ~ Treatment*Sex, data = .x)))) %>% 
  unnest(t_test) %>%  
  select(one_of(c("Metabolite","term", "p.value"))) %>% 
  arrange(p.value) %>% 
  drop_na()


t_df <- dfgraph %>%
  group_by(Metabolite) %>% 
  nest() %>% 
  mutate(t_test = map(data, ~tidy(TukeyHSD(aov(value ~ Treatment*Sex, data = .x))))) %>%
  unnest(t_test) %>%  
  select(one_of(c("Metabolite","contrast", "adj.p.value"))) %>% 
  arrange(adj.p.value)

write_csv(p_df,"export/StatinLiverANOVA.csv")
write_csv(t_df,"export/StatinLiverHSD.csv")

```



