---
title: "De novo lipogenesis in HepG2 cells"
author: Alec Trub
output: html_notebook
---
#Figures for DNL

## Load libraries
```{r}
library(tidyverse) # for base packages
library(readxl) # to read excel files; part of tidyverse, but not a core part, so need to load it separately
library(janitor) # clean data
library(viridis) # For awesome, accessible color palettes
library(ggrepel) #for smart ggplot labels
library(broom) #for stats
library(cowplot)
```

##Load data set containing proteins and statistical information. Clean up extra rows
```{r}
df <- read_excel("data/data.xlsx",col_names = TRUE)%>%
  remove_empty(c("rows", "cols"))

```

#Arrange data as % labeled
```{r}
#Mutate data to 1-M0
df= mutate(df,labeled = 100 - `M0`)

#Factors
df$Hours = factor(df$Hours)

```

#figures
```{r}
#
ggplot(df,aes(x = Hours, y = labeled, fill = Treatment))+
  geom_boxplot(position = "dodge")+
  theme_cowplot()+
  scale_fill_viridis(discrete = T)+
  labs( title = "", y = "% labeled palmitate")+
  theme(axis.text = element_text(size = 20, face = "bold"), legend.position = "bottom", axis.title = element_text(size = 20, face = "bold"), legend.text = element_text(size = 20), legend.title = element_text(size = 20, face = "bold"))

ggsave("InCellDNL_BOX.tiff", width = 9, height = 7)
```



#stats
```{r}
#ANOVA

p_df <- df %>%
  nest() %>% #Nest all non-grouping columns into list-frames
  mutate(t_test = map(data, ~tidy(aov(labeled ~ Treatment * Hours, data = .x)))) %>% 
  unnest(t_test) %>%  
  select(c("term", "p.value")) %>% 
  arrange(p.value)
  


write.table(p_df,file = "aov.txt")

 
```


